require('dotenv').config();
const express = require('express');
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const cors = require('cors');
const winston = require('winston');
require('winston-daily-rotate-file');

const app = express();
const PORT = process.env.PORT || 3000;
const MEDIAMTX_HLS_PORT = parseInt(process.env.MEDIAMTX_HLS_PORT || '8888');
const MEDIAMTX_WEBRTC_PORT = parseInt(process.env.MEDIAMTX_WEBRTC_PORT || '8889');
const MEDIAMTX_BIN = process.env.MEDIAMTX_BIN || 'mediamtx';

// Configure rotating logs
const logger = winston.createLogger({
  level: 'info',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.printf(({ timestamp, level, message }) => `${timestamp} [${level}]: ${message}`)
  ),
  transports: [
    new winston.transports.DailyRotateFile({
      filename: 'service-%DATE%.log',
      datePattern: 'YYYY-MM-DD',
      maxSize: '50m',
      maxFiles: '1d',
    }),
    new winston.transports.DailyRotateFile({
      filename: 'service-error-%DATE%.log',
      datePattern: 'YYYY-MM-DD',
      level: 'error',
      maxSize: '50m',
      maxFiles: '1d',
    }),
    new winston.transports.Console(),
  ],
});

app.use(cors());
app.use(express.static('public'));

const cameras = [];
let mediamtxProcess = null;

function loadCameras() {
  try {
    const data = fs.readFileSync('cameras.txt', 'utf8');
    const lines = data.split('\n').filter((line) => line.trim() !== '');
    lines.forEach((line, index) => {
      const [name, url] = line.split(';');
      if (name && url) {
        cameras.push({
          id: index + 1,
          name: name.trim(),
          url: url.trim(),
          slug: `cam${index + 1}`,
        });
      }
    });
    logger.info(`Loaded ${cameras.length} cameras: ${cameras.map((c) => c.name).join(', ')}`);
  } catch (err) {
    logger.error(`Error reading cameras.txt: ${err.message}`);
  }
}

function generateMediamtxYaml() {
  const pathsSection = cameras
    .map((cam) => `  ${cam.slug}:\n    source: ${cam.url}\n    rtspTransport: tcp`)
    .join('\n');

  return `# Generated by cameras-echo server
logLevel: warn
logDestinations: [stdout]

# RTSP (internal use only)
rtsp: true
rtspAddress: :8554

# HLS (for Echo Show / fallback browsers)
# LL-HLS: latency ≈ 3x hlsPartDuration (~600ms)
hls: true
hlsAddress: :${MEDIAMTX_HLS_PORT}
hlsAllowOrigins: ['*']
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsAlwaysRemux: true

# WebRTC (primary - near real-time)
webrtc: true
webrtcAddress: :${MEDIAMTX_WEBRTC_PORT}
webrtcAllowOrigins: ['*']
webrtcLocalUDPAddress: :8189
webrtcIPsFromInterfaces: true

# Disabled protocols
srt: false
api: false

paths:
${pathsSection}
`;
}

function startMediamtx() {
  const configPath = path.join(__dirname, 'mediamtx-runtime.yml');
  fs.writeFileSync(configPath, generateMediamtxYaml());
  logger.info('Starting mediamtx...');

  mediamtxProcess = spawn(MEDIAMTX_BIN, [configPath], { stdio: 'inherit' });

  mediamtxProcess.on('exit', (code) => {
    logger.warn(`mediamtx exited (code ${code}), restarting in 5s...`);
    mediamtxProcess = null;
    setTimeout(startMediamtx, 5000);
  });

  mediamtxProcess.on('error', (err) => {
    logger.error(`Failed to start mediamtx: ${err.message}`);
    logger.error(`Make sure mediamtx is installed: brew install mediamtx`);
  });
}

// Camera list API
app.get('/api/cameras', (req, res) => {
  res.json({
    cameras: cameras.map((c) => ({
      id: c.id,
      name: c.name,
      slug: c.slug,
    })),
    ports: {
      hls: MEDIAMTX_HLS_PORT,
      webrtc: MEDIAMTX_WEBRTC_PORT,
    },
  });
});

// Restart endpoint (no-op: mediamtx handles reconnection internally)
app.post('/api/restart/:id', (req, res) => {
  logger.info(`Restart requested for camera ${req.params.id} (handled by mediamtx internally)`);
  res.json({ ok: true });
});

// Start server
app.listen(PORT, () => {
  logger.info(`Server running at http://localhost:${PORT}`);
  loadCameras();
  startMediamtx();
});

// Graceful shutdown
process.on('SIGINT', () => {
  logger.info('Shutting down...');
  if (mediamtxProcess) {
    mediamtxProcess.kill('SIGTERM');
  }
  process.exit(0);
});

process.on('SIGTERM', () => {
  if (mediamtxProcess) {
    mediamtxProcess.kill('SIGTERM');
  }
  process.exit(0);
});
